apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: default
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER_KEY: admin
  RABBITMQ_DEFAULT_PASS_KEY: myAdmin1
  RABBITMQ_ENABLED_PLUGINS_KEY: |
    [rabbitmq_management,rabbitmq_prometheus].
  RABBITMQ_CONFIG_KEY: |
    ## CUSTOM SETTINGS ARE NOT MEANT TO BE TAKEN STRAIGHT INTO PRODUCTION
    ## see https://www.rabbitmq.com/configure.html for further information
    ## on configuring RabbitMQ

    ## allow access to the guest user from anywhere on the network
    ## https://www.rabbitmq.com/access-control.html#loopback-users
    ## https://www.rabbitmq.com/production-checklist.html#users
    loopback_users.guest = false

    ## Send all logs to stdout/TTY. Necessary to see logs when running via
    ## a container
    log.console = true
