apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-volume
  namespace: default
spec:
  storageClassName: local-path
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/Users/sorriso/Documents/GitHub/kube-rabbitmq-dockerhub/volume/data"
  capacity:
    storage: 1Gi
  claimRef:
    name: rabbitmq-volume-claim
    namespace: default
