apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: default
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.9.21-management-alpine
          imagePullPolicy: Never
          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 15
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: 5672
            failureThreshold: 6
            initialDelaySeconds: 15
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          ports:
          - containerPort: 5672
            protocol: TCP
          - containerPort: 15672
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 512Mi
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: RABBITMQ_DEFAULT_USER_KEY
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: RABBITMQ_DEFAULT_PASS_KEY
          volumeMounts:
            - name: rabbitmq-storage
              mountPath: /var/lib/rabbitmq/
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq/conf.d/10-defaults.conf
              subPath: RABBITMQ_CONFIG_KEY
              readOnly: true
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq/enabled_plugins
              subPath: RABBITMQ_ENABLED_PLUGINS_KEY
              readOnly: true
      volumes:
        - name: rabbitmq-storage
          persistentVolumeClaim:
            claimName: rabbitmq-volume-claim
        - name: rabbitmq-config
          secret:
            secretName: rabbitmq-secret
