apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq-service
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: rabbitmq-gui
      protocol: TCP
      port: 15672
      targetPort: 15672
